name: dart_pro
description: Dart语言学习项目
version: 1.0.0
homepage: https://github.com/Mr-Cai/dart_pro
author: 蔡凯歌 <caikaige.g@gmail.com>

environment:
  sdk: '>=2.6.0-dev.1.0 <3.0.0'

dependencies:
  path: 

dev_dependencies:
  pedantic: 
  test: 
