name: dart_pro
description: Dart语言学习项目
version: 1.0.0
homepage: https://github.com/Mr-Cai/dart_pro
author: 蔡凯歌 <caikaige.g@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.4
  json_annotation: ^3.0.1
  meta: ^1.1.8
  dio: ^3.0.9

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  build_runner: ^1.8.0
  freezed: ^0.2.2
  json_serializable: ^3.2.5